//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChecadorHonorarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.inAndOutHistories = new HashSet<inAndOutHistory>();
        }
    
        public short userID { get; set; }
        public short scheduleID { get; set; }
        public short fingerprintID { get; set; }
        public System.DateTime birthday { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string lastname2 { get; set; }
        public string jobPosition { get; set; }
        public string email { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual fingerprint fingerprint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inAndOutHistory> inAndOutHistories { get; set; }
        public virtual schedule schedule { get; set; }
    }
}
