//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChecadorHonorarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_user_filter_deleted
    {
        public short Identificador { get; set; }
        public string Nombre { get; set; }
        public string Apellido_Paterno { get; set; }
        public string Apellido_Materno { get; set; }
        public System.DateTime Fecha_de_Nacimiento { get; set; }
        public string Puesto { get; set; }
        public string Correo { get; set; }
        public bool Estado { get; set; }
    }
}
