//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChecadorHonorarios
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Honorarios_Check_DGTITEntities : DbContext
    {
        public Honorarios_Check_DGTITEntities()
            : base("name=Honorarios_Check_DGTITEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administrator> administrators { get; set; }
        public virtual DbSet<daysIn> daysIns { get; set; }
        public virtual DbSet<fingerprint> fingerprints { get; set; }
        public virtual DbSet<inAndOutHistory> inAndOutHistories { get; set; }
        public virtual DbSet<schedule> schedules { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<verifyCheck> verifyChecks { get; set; }
    }
}
