//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChecadorHonorarios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class administrator
    {
        public short administratorID { get; set; }
        public string admPassword { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string lastname2 { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public Nullable<bool> addAdmin { get; set; }
    }
}
