//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChecadorHonorarios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class verifyCheck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public verifyCheck()
        {
            this.inAndOutHistories = new HashSet<inAndOutHistory>();
        }
    
        public short verifyCheckID { get; set; }
        public short fingerprintID { get; set; }
        public System.DateTime checkDate { get; set; }
        public System.TimeSpan checkTime { get; set; }
    
        public virtual fingerprint fingerprint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inAndOutHistory> inAndOutHistories { get; set; }
    }
}
